"""v34: protected content layers and uncropped workshop visuals."""
from pathlib import Path
import html,json
from PIL import Image
R=Path(__file__).resolve().parents[1]
D=json.loads((R/'tools/projects.json').read_text())
O=json.loads((R/'tools/original-projects.json').read_text())
E=html.escape
P=''

def img(path,alt='',cls='',eager=False,zoom=False):
 with Image.open(R/path) as im:w,h=im.size
 tag=f'<img src="{P}{path}?v=34" alt="{E(alt)}" class="{cls}" width="{w}" height="{h}" loading="{"eager" if eager else "lazy"}" decoding="async"'+(' fetchpriority="high"' if eager else '')+'>'
 if zoom:return f'<a class="zoom" href="{P}{path}" data-zoom data-caption="{E(alt)}" aria-label="Рассмотреть: {E(alt)}">{tag}<span class="zoom-label" aria-hidden="true">Рассмотреть ↗</span></a>'
 return tag

def decor(name,cls=''):
 return f'<span class="decor-object {cls}" aria-hidden="true">{img("assets/img/decor/object-"+name+".webp","")}</span>'

def divider(name='ribbons'):
 return ''

def mascot(pose='urban-neutral',cls='',live=False):
 return f'<div class="mascot-scene {cls}" data-default-pose="{pose}"'+(' data-mascot' if live else '')+f'><div class="mascot-body">{img("assets/img/mascot/"+pose+".webp","","mascot-image",pose=="urban-neutral")}</div></div>'

def btn(href,text,kind='solid',attrs=''):
 return f'<a class="button {kind}" href="{href}" {attrs}>{text}<span aria-hidden="true">↗</span></a>'

def head(title,desc):
 return f'<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f3ef"><title>{E(title)}</title><meta name="description" content="{E(desc)}"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(desc)}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><link rel="icon" href="{P}assets/favicon.svg"><link rel="preload" href="{P}assets/fonts/manrope-regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="{P}assets/css/styles.css?v=34"><script src="{P}assets/js/main.js?v=34" defer></script></head>'

def header(home=False):
 b='' if home else P+'index.html'
 return f'<a class="skip" href="#main">К содержанию</a><header class="site-header"><div class="wrap header-row"><a class="brand" href="{b}#home" aria-label="Диана Тхайцухова — главная">soulminori<span aria-hidden="true">✳</span></a><nav aria-label="Основная навигация"><a href="{b}#projects">Проекты</a><a href="{b}#workshop">Хуторок</a><a href="{b}#about">Обо мне</a></nav><a class="header-contact" href="{b}#contact">Написать ↗</a><button type="button" class="motion-toggle" aria-pressed="false" aria-label="Отключить анимацию" title="Отключить анимацию">Ⅱ</button></div></header>'

def footer():
 return f'<footer class="wrap footer"><span>© 2026 · Диана Тхайцухова</span><a href="{P}index.html#projects">Графический дизайн · UX/UI</a><a href="#top">Наверх ↑</a></footer><div class="toast" role="status" aria-live="polite"></div><dialog class="lightbox" aria-labelledby="lightbox-caption"><div class="lightbox-bar"><p id="lightbox-caption"></p><button type="button" data-close aria-label="Закрыть изображение">✕</button></div><div class="lightbox-stage"><img alt=""></div><div class="lightbox-bar"><button type="button" data-prev aria-label="Предыдущее изображение">←</button><span data-count></span><a data-original href="#top" target="_blank" rel="noopener">Открыть оригинал ↗</a><button type="button" data-next aria-label="Следующее изображение">→</button></div></dialog></body></html>'

def contacts():
 return f'<section class="contact noise-panel" id="contact"><div class="wrap contact-grid"><div><p class="eyebrow">05 / На связи</p><h2>Давайте сделаем<br><em>что-то сильное.</em></h2><p>Сейчас я открыта к работе графическим или UX/UI-дизайнером. Если вам нужен человек, который умеет собрать идею в систему и довести её до реального носителя, — напишите мне.</p><div class="actions">{btn("https://t.me/soulminori","Написать в Telegram","light", "target=\"_blank\" rel=\"noopener\"")}{btn("assets/docs/diana-tkhaytsukhova-resume.pdf","Скачать резюме · PDF","outline-light","download")}</div></div><div class="contact-addresses"><p class="contact-location">Санкт-Петербург · открыта к удалённой работе</p><a href="tel:+79513857017"><span>Позвонить</span><strong>+7 951 385-70-17</strong></a><a href="mailto:Soulminori2.0@gmail.com"><span>Написать на почту</span><strong>Soulminori2.0@gmail.com</strong></a><button type="button" data-copy-email>Скопировать почту ⧉</button><a href="https://t.me/soulminori" target="_blank" rel="noopener"><span>Telegram — отвечаю быстрее всего</span><strong>@soulminori</strong></a><div class="socials"><a href="https://vk.ru/soulmi_nori" target="_blank" rel="noopener">VK ↗</a><a href="https://www.instagram.com/soulmi_nori/" target="_blank" rel="noopener">Instagram ↗</a></div></div></div>{decor('star','contact-star')}</section>'

ABOUT=[
 ('profile','Кто я','urban-wave','Я люблю, когда идея<br>становится <em>вещью.</em>','<p class="lead">Привет! Я Диана, графический дизайнер из Санкт-Петербурга. Больше всего мне нравятся проекты, где одного красивого кадра мало: нужно придумать характер, выстроить правила и аккуратно перенести их на десятки форматов.</p><p>Я работаю с айдентикой, упаковкой, полиграфией и редакционным дизайном, а сейчас развиваюсь в UX/UI. Мне близок дизайн, который не только хорошо выглядит, но и помогает человеку быстро понять главное.</p><p>Ещё у меня есть мастерская «Хуторок». Там я проверяю идеи руками — через гипс, свечи, живопись и 3D-печать.</p>'),
 ('practice','Опыт','urban-present','Знаю путь<br>от макета до <em>производства.</em>','<div class="experience-item"><p class="eyebrow">Июль 2025 — сейчас</p><h4>Дизайнер-декоратор · проектная работа</h4><p>Развиваю визуальный образ мастерской: упаковку, этикетки, открытки, материалы для соцсетей и оформление индивидуальных заказов. Готовлю макеты с учётом размеров, сгибов, вырубки и печати.</p></div><div class="experience-item"><p class="eyebrow">Апрель 2023 — сейчас</p><h4>Графический дизайнер · фриланс</h4><p>Создаю айдентику, рекламные материалы, упаковку, презентации и полиграфию. Работаю от референсов и первых вариантов до правок, адаптаций и аккуратно собранных файлов для передачи.</p></div><div class="experience-item"><p class="eyebrow">Сентябрь 2025 — май 2026</p><h4>Художник-конструктор · АО НПК «Северная заря»</h4><p>Разрабатывала эскизы, визуальные концепции и документацию, сопровождала изделия до передачи в производство. Согласовывала решения с инженерами и технологами и дорабатывала материалы после проверок.</p></div>'),
 ('skills','Что умею','urban-work','Собираю не кадр,<br>а <em>работающую систему.</em>','<p class="lead">Айдентика и фирменные носители, упаковка, композиция, типографика, многостраничная вёрстка, подготовка файлов к печати, цифровые макеты и прототипы.</p><div class="tool-grid"><span>Illustrator<small>Логотипы и вектор</small></span><span>Photoshop<small>Изображения и мокапы</small></span><span>InDesign<small>Книги и полиграфия</small></span><span>Figma<small>Интерфейсы и прототипы</small></span></div><p>Также работаю в PowerPoint и использую AI-инструменты там, где они помогают быстрее проверить идею или подготовить материал — финальное решение и контроль всегда остаются за мной.</p>'),
 ('education','Образование','urban-think','Дизайн встречается<br>с <em>технологиями.</em>','<div class="education"><span>2028</span><div><h4>СПбГУПТД</h4><p>«Искусственный интеллект в информационных системах». Учусь сейчас, планируемое окончание — 2028 год.</p></div></div><div class="education"><span>2025</span><div><h4>Колледж технологии, моделирования и управления СПбГУПТД</h4><p>«Дизайн по отраслям», направление промышленного дизайна. Среднее профессиональное образование.</p></div></div><p>Русский — родной. Английский — B1.</p>'),
 ('process','Как работаю','urban-idea','Сначала задаю вопросы.<br>Потом <em>рисую.</em>','<ol class="steps"><li><strong>Разбираюсь в задаче</strong><p>Кому и зачем нужен дизайн, где человек его увидит, какие есть ограничения.</p></li><li><strong>Нахожу направление</strong><p>Собираю референсы, формулирую идею и показываю, почему она подходит задаче.</p></li><li><strong>Строю систему</strong><p>Настраиваю композицию, типографику, цвет и правила, чтобы решение держалось на разных форматах.</p></li><li><strong>Довожу до передачи</strong><p>Проверяю адаптации, готовлю файлы и остаюсь на связи во время правок или запуска.</p></li></ol>'),
 ('team','В команде','urban-wave','Говорю по делу<br>и спокойно отношусь к <em>правкам.</em>','<p class="lead">Умею объяснять дизайн простыми словами, слышать обратную связь и не воспринимать обсуждение макета как спор о вкусах.</p><p>В команде я внимательна к срокам, именам файлов и договорённостям. Если вижу риск для результата, поднимаю вопрос заранее и предлагаю варианты.</p><h4>Что ищу сейчас</h4><p>Полную занятость графическим или UX/UI-дизайнером в команде, где ценят сильную визуальную идею, аккуратную реализацию и желание расти. Рассматриваю удалённую работу.</p>')]

def home():
 global P
 P=''
 cards=[]
 for i,(k,d) in enumerate(D.items(),1):
  cards.append(f'<article class="project-card" id="project-{k}" data-reveal><a class="project-cover" href="projects/{k}.html">{img("assets/img/projects/"+k+"/"+d["cover"],d["title"]+" — "+d["short"])}<span class="cover-pill">Открыть кейс ↗</span></a><div class="project-meta"><span>{i:02d} / {E(d["category"])}</span></div><h3><a href="projects/{k}.html">{E(d["title"])}<span aria-hidden="true">↗</span></a></h3><p>{E(d["short"])}</p></article>')
 others=[('severnaya-zarya','Северная заря','Реализован','Эскизы и визуальная документация для промышленного производства'),('gastro-port','GASTRO PORT','Реализован','Графика и носители для гастрономического пространства'),('nordax','NORDAX','Концепция','Айдентика для бренда с промышленным характером'),('atlas-tishiny','Атлас тишины','Концепция','Редакционная история о тишине и наблюдении'),('cherta','Черта','Концепция','Минималистичная система знака и визуальных носителей')]
 extra=''.join(f'<article class="other-card" data-reveal>{img("assets/img/projects/other/"+k+".webp",name+" — "+desc,zoom=True)}<div><h4>{name}</h4><span class="status {"real" if status=="Реализованный" else ""}">{status}</span></div><p>{desc}</p></article>' for k,name,status,desc in others)
 tabs=''.join(f'<button type="button" role="tab" id="tab-{key}" aria-controls="panel-{key}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-pose="{pose}"><span>{i+1:02d}</span>{label}<i aria-hidden="true">↗</i></button>' for i,(key,label,pose,title,body) in enumerate(ABOUT))
 panels=''.join(f'<section id="panel-{key}" role="tabpanel" aria-labelledby="tab-{key}" tabindex="0" {"hidden" if i else ""}><h3>{title}</h3>{body}</section>' for i,(key,label,pose,title,body) in enumerate(ABOUT))
 ticker='<span>Айдентика</span><b aria-hidden="true">✳</b><span>Упаковка</span><b aria-hidden="true">✳</b><span>Редакционный дизайн</span><b aria-hidden="true">✳</b><span>UX/UI</span><b aria-hidden="true">✳</b>'
 return head('Диана Тхайцухова — графический дизайнер / UX/UI','Айдентика, упаковка и цифровые проекты Дианы Тхайцуховой. Опыт работы с печатью, производством и визуальными системами.')+f'''<body id="top">{header(True)}<main id="main">
<section class="wrap hero" id="home"><div class="hero-copy"><p class="eyebrow">Графический дизайнер · развиваюсь в UX/UI</p><h1><span>Диана</span><span>Тхайцухова<span class="accent-dot">.</span></span></h1><p class="hero-line">Идеи становятся<br><span class="gradient-text">понятными и живыми.</span></p><p class="hero-description">Люблю превращать сложную идею в образ, который легко понять и запомнить. Работаю с айдентикой, упаковкой и цифровыми макетами — от первого наброска до готовых файлов.</p><div class="actions">{btn('#projects','Посмотреть кейсы','solid','data-hero-cta')}{btn('assets/docs/diana-tkhaytsukhova-resume.pdf','Резюме · PDF','outline','download')}</div><p class="availability"><span aria-hidden="true"></span> Открыта к предложениям · Санкт-Петербург / удалённо</p><a class="hero-telegram" href="https://t.me/soulminori" target="_blank" rel="noopener">Написать в Telegram · @soulminori ↗</a><a class="hero-phone" href="tel:+79513857017">+7 951 385-70-17</a></div><div class="hero-stage noise-panel"><div class="hero-halo" aria-hidden="true"></div><span class="floating-label">Между пикселем<br>и предметом</span><span class="hero-asterisk" aria-hidden="true">✳</span>{decor('ribbon','hero-decor-one')}{decor('star','hero-decor-two')}{mascot('urban-neutral','hero-character',True)}<button type="button" class="hello-button" data-greet>Привет, я Диана <span aria-hidden="true">↗</span></button><span class="stage-coordinate" aria-hidden="true">ИДЕЯ → СИСТЕМА → НОСИТЕЛЬ</span></div></section>
<div class="ticker" aria-label="Айдентика, упаковка, редакционный дизайн и UX/UI"><div class="ticker-track"><div>{ticker}</div><div aria-hidden="true">{ticker}</div></div></div>
<section id="projects" class="wrap section"><div class="section-heading"><div><p class="eyebrow">01—04 / Избранные кейсы</p><h2>Четыре проекта.<br>Четыре <em>разных характера.</em></h2></div><p>Внутри — не только финальные картинки, но и моя логика: задача, идея, система и работа с носителями.</p></div>{decor('loop','projects-decor')}<div class="project-grid">{''.join(cards)}</div><div class="other-heading"><h3>Другие работы</h3><p>Два реализованных проекта и три авторские концепции</p></div><div class="other-grid">{extra}</div></section>
{divider('ribbons')}
<section class="workshop-teaser noise-panel" id="workshop"><div class="wrap workshop-teaser-grid"><div><p class="eyebrow">03 / Авторская мастерская</p><h2>Иногда лучший способ<br>понять форму — <em>сделать её руками.</em></h2><p class="lead">«Хуторок» — моя мастерская, где появляются свечи, гипсовый декор, картины и предметы, напечатанные на 3D-принтере.</p><p>Здесь я отвечаю и за визуальный образ, и за сами вещи: придумываю коллекции, фотографирую, оформляю соцсети и готовлю заказы.</p><div class="chips"><span>Мастер-классы</span><span>Авторские изделия</span><span>3D-печать</span></div>{btn('workshop.html','Посмотреть мастерскую','light')}</div><div class="workshop-composition"><div class="workshop-photo">{img('assets/img/workshop/handmade-07-pink-set.webp','Свечи и подарочный набор мастерской Хуторок')}</div>{mascot('workshop-vase','teaser-character')}{decor('petals','workshop-decor')}<span class="paper-note">Придумать.<br>Сделать.<br>Потрогать.</span></div></div></section>
{divider('sculpture')}
<section id="about" class="wrap section about"><div class="section-heading"><div><p class="eyebrow">04 / Обо мне</p><h2>Не только работы,<br>но и человек <em>за ними.</em></h2></div><p>Здесь — мой опыт, инструменты, образование и то, как я веду проекты.</p></div>{decor('cloud','about-decor')}<div class="about-desk"><div class="about-navigation"><p class="eyebrow">Выберите раздел</p><div role="tablist" aria-label="Разделы обо мне" aria-orientation="vertical">{tabs}</div><a class="text-link" href="assets/docs/diana-tkhaytsukhova-resume.pdf" download>Скачать резюме · PDF ↓</a></div><div class="about-content noise-panel">{panels}</div><aside class="about-companion" aria-hidden="true">{mascot('urban-wave')}<span class="companion-note">Приятно познакомиться!</span></aside></div></section>{contacts()}</main>{footer()}'''

NOTES={
 'govori':('Говорить — значит<br>быть <em>услышанным.</em>','01-event.webp','Я строила систему так, чтобы у каждого формата была своя громкость: плакат может говорить смело, буклет — спокойно объяснять, а мерч — работать как личное высказывание.','Проверить знак в малом размере, собрать правила типографики и адаптировать систему под программу и размеры реального события.'),
 'buro':('Сохранить то,<br>что нельзя <em>потрогать.</em>','02-kiosk-route.webp','Для меня было важно придумать не только внешний вид, но и путь человека: заметить указатель, дойти до бюро, выбрать карточку, записать историю и оставить её в архиве.','Провести тест маршрута с участниками, проверить понятность текстов и доступность городской точки, затем уточнить конструкцию объектов.'),
 'language':('Понять другого.<br>И немного лучше — <em>себя.</em>','01-set.webp','В основной книге важны ритм чтения и ясная иерархия. В дневнике — воздух и свобода для собственных записей. Я оставила им разный характер, но связала одной пластикой.','Отредактировать полный текст, напечатать пробный экземпляр и проверить, удобно ли долго читать книгу и заполнять дневник от руки.'),
 'calmes':('Ужин заканчивается.<br>Впечатление <em>остаётся.</em>','03-packaging.webp','На этикетке главным становится знак, на большой коробке — паттерн, а на развёртке видно, как графика продолжает жить на сгибах и внутренних поверхностях.','Сверить развёртки с требованиями производителя, сделать цветопробу и проверить материалы на реальном комплекте упаковки.')}

def case(k,index):
 global P
 P='../'
 d=D[k];hook,hero,bridge,nextstep=NOTES[k]
 gallery=[]
 for src,label,span,fit,note in O[k]['images']:
  name=Path(src).name
  if name in d['omit'] or name==hero:continue
  caption=d['captions'].get(name,label)
  gallery.append(f'<figure class="case-figure {"wide" if span==12 else ""}" data-reveal>{img(src,caption,zoom=True)}<figcaption><span>{len(gallery)+1:02d}</span>{E(caption)}</figcaption></figure>')
 decisions=''.join(f'<article data-reveal><span class="decision-no">0{i}</span><h3>{E(t)}</h3><p>{E(b)}</p></article>' for i,(t,b) in enumerate(d['decisions'],1))
 nk=list(D)[(index+1)%4]
 return head(d['title']+' — кейс Дианы Тхайцуховой',d['lead'])+f'''<body id="top" class="case-page case-{k}" style="--project-color:{d['accent']}">{header()}<main id="main"><div class="wrap breadcrumb"><a href="../index.html#project-{k}">← Все проекты</a><span>Кейс {index+1:02d} / 04</span></div><section class="wrap case-title"><p class="eyebrow">{E(d['category'])}</p><h1>{E(d['title'])}</h1><div class="case-summary"><p class="lead">{E(d['lead'])}</p><span class="status">Концептуальный проект · готов к реализации</span><button class="text-link" type="button" data-copy-link>Скопировать ссылку ↗</button></div>{decor({'govori':'ribbon','buro':'rings','language':'cloud','calmes':'flower'}[k],'case-title-decor')}</section><figure class="case-opening noise-panel">{img('assets/img/projects/'+k+'/'+hero,d['title']+' — ключевая визуализация',eager=True,zoom=True)}<figcaption>Ключевой кадр проекта</figcaption></figure><nav class="case-nav" aria-label="Главы кейса"><div class="wrap"><a href="#brief">01 · О задаче</a><a href="#system">02 · Мои решения</a><a href="#gallery">03 · Что получилось</a><a href="#result">04 · Дальше</a></div></nav>
<section id="brief" class="wrap section case-brief"><div><p class="eyebrow">01 / От задачи к идее</p><h2>{hook}</h2></div><div><h3>Что нужно было решить</h3><p>{E(d['task'])}</p><h3>На чём построена идея</h3><p>{E(d['idea'])}</p><h3>За что отвечала я</h3><p>{E(d['scope'])}</p></div></section>{divider('paper' if k in ('govori','language') else 'plaster')}<section id="system" class="case-system noise-panel"><div class="wrap"><p class="eyebrow">02 / Почему это работает</p><h2>Решения, которые<br><em>держат систему.</em></h2><div class="decision-grid">{decisions}</div><div class="case-bridge"><p class="lead">{E(bridge)}</p><span aria-hidden="true">✳</span></div></div></section><section id="gallery" class="wrap section"><div class="section-heading"><div><p class="eyebrow">03 / Макеты и носители</p><h2>Теперь можно<br><em>рассмотреть ближе.</em></h2></div><p>Под каждым изображением — точная подпись. Нажмите на работу, чтобы открыть её крупнее.</p></div><div class="case-gallery">{''.join(gallery)}</div></section>{divider('collage' if k in ('buro','calmes') else 'icons')}<section id="result" class="wrap case-result"><div><p class="eyebrow">04 / Итог</p><h2>Что проект показывает обо мне</h2><p class="lead">{E(d['outcome'])}</p><details><summary>Что я проверила бы перед запуском</summary><p>{E(nextstep)}</p></details>{btn('../index.html#contact','Обсудить со мной проект')}</div>{mascot({'govori':'urban-point','buro':'urban-crouch','language':'urban-tablet','calmes':'urban-present'}[k],'result-character')}</section><nav class="wrap next-case" aria-label="Следующий проект"><a href="{nk}.html"><span class="eyebrow">Следующий кейс / {(index+1)%4+1:02d}</span><strong>{E(D[nk]['title'])}</strong><span aria-hidden="true">↗</span></a></nav></main>{footer()}'''

def figures(items):
 return ''.join(f'<figure data-reveal>{img("assets/img/workshop/"+f,label,zoom=True)}<figcaption>{label}</figcaption></figure>' for f,label in items)

def workshop():
 global P
 P=''
 slides=[('01-cover','Знакомство'),('02-about','О мастерской'),('03-masterclasses','Мастер-классы'),('04-handmade','Ручная работа'),('05-values','Ценности'),('06-cta','Приглашение')]
 carousel=''.join(f'<figure class="story-slide" id="slide-{i}" role="group" aria-label="Слайд {i} из 6: {label}">{img("assets/img/workshop/carousel-"+name+".webp",label,zoom=True)}</figure>' for i,(name,label) in enumerate(slides,1))
 dots=''.join(f'<button type="button" data-slide="{i}" aria-label="Показать слайд {i+1}" aria-current="{str(i==0).lower()}"></button>' for i in range(6))
 handmade=[('handmade-07-pink-set.webp','Свечи и подарочные наборы'),('handmade-08-shell-candles.webp','Свечи-ракушки'),('handmade-01-leaf-trays.webp','Гипсовые подносы с росписью'),('handmade-10-cat-coasters.webp','Расписные подставки'),('handmade-05-mountain-painting.webp','Текстурная картина'),('handmade-04-flower-painting.webp','Интерьерная работа'),('handmade-06-marbled-coasters.webp','Мраморные подставки'),('handmade-09-sunflower-set.webp','Набор с подсолнухами'),('handmade-11-sea-heart.webp','Морская композиция'),('handmade-02-blue-set.webp','Голубой набор'),('handmade-03-painted-trays.webp','Декоративные тарелки')]
 return head('Хуторок — мастерская Дианы Тхайцуховой','Мастер-классы, авторские свечи, гипсовый декор, картины и 3D-печать в мастерской Дианы Тхайцуховой.')+f'''<body id="top" class="workshop-page">{header()}<main id="main"><div class="wrap breadcrumb"><a href="index.html#workshop">← К портфолио</a><span>Моя предметная практика</span></div><section class="wrap workshop-hero"><div><p class="eyebrow">Авторская творческая мастерская</p><h1>Хуторок<span class="accent-dot">.</span></h1><p class="hero-line">Здесь можно замедлиться<br>и <em>сделать своё.</em></p><p class="lead">Я создала «Хуторок» как место для спокойного творчества: провожу мастер-классы, делаю небольшие серии предметов и беру индивидуальные заказы.</p>{btn('https://vk.ru/hutorokdesign','Написать в мастерскую','solid','target="_blank" rel="noopener"')}</div><div class="workshop-hero-art noise-panel">{mascot('workshop-vase','',True)}{decor('pebbles','workshop-hero-decor')}<span class="paper-note">Свечи · гипс · картины<br>и 3D-печать</span></div></section><nav class="wrap workshop-nav" aria-label="Направления мастерской"><a href="#classes"><span>01</span>Мастер-классы ↘</a><a href="#handmade"><span>02</span>Авторские изделия ↘</a><a href="#printing"><span>03</span>3D-печать ↘</a></nav>
<section class="wrap section workshop-intro"><p class="eyebrow">Что такое «Хуторок»</p><h2>От идеи на экране<br>до вещи <em>в руках.</em></h2><p class="lead">Для меня мастерская — не отдельное хобби, а ещё одна часть дизайнерской практики. Я продумываю визуальный стиль, коллекции, упаковку и контент, а затем сама работаю с материалом. Поэтому хорошо понимаю, что происходит с макетом после красивой презентации.</p>{img('assets/img/workshop/brand-banner.webp','Фирменная графика и настроение мастерской Хуторок','workshop-banner')}</section>
{divider('icons')}
<section class="story-section noise-panel"><div class="wrap story-layout"><div class="story-intro"><p class="eyebrow">Карусель постов / 06</p><h2>Как мастерская<br><em>говорит о себе.</em></h2><p>Это серия публикаций для соцсетей. За одно нажатие или свайп меняется ровно один пост.</p><div class="story-controls"><button type="button" data-carousel-prev aria-label="Предыдущий пост">←</button><span><b data-carousel-current>01</b> / 06</span><button type="button" data-carousel-next aria-label="Следующий пост">→</button></div><div class="story-dots">{dots}</div><div class="carousel-guide">{mascot("workshop-wave","carousel-character")}<p class="small">Листайте по одному<br>стрелками или свайпом.</p></div></div><div class="carousel" tabindex="0" role="region" aria-label="Карусель постов мастерской">{carousel}</div></div></section>
<section id="classes" class="wrap section"><div class="section-heading"><div><p class="eyebrow">01 / Мастер-классы</p><h2>Не нужно уметь.<br>Достаточно <em>хотеть попробовать.</em></h2></div><p>Занятия по свечам, гипсовому декору и текстурным картинам — с материалами и моей помощью на каждом этапе.</p></div><div class="classes-grid"><div class="class-image noise-panel">{img('assets/img/workshop/handmade-05-mountain-painting.webp','Текстурная картина с горным рельефом')}</div><div><h3>Что происходит на занятии</h3><p>Сначала выбираем идею и настроение работы, потом знакомимся с материалом и постепенно собираем предмет. Я показываю приёмы, помогаю с композицией и не заставляю всех делать одинаково.</p><ol class="steps"><li><strong>Находим идею</strong><p>Выбираем форму, палитру и примеры, от которых хочется оттолкнуться.</p></li><li><strong>Работаем с материалом</strong><p>Я объясняю этапы и помогаю там, где важны техника и аккуратность.</p></li><li><strong>Доводим детали</strong><p>Добавляем роспись или декор. Если материалу нужно высохнуть, заранее договариваемся о выдаче.</p></li></ol>{btn('https://vk.ru/hutorokdesign','Узнать о ближайших занятиях','outline','target="_blank" rel="noopener"')}</div></div></section>
{divider('plaster')}
<section id="handmade" class="wrap section handmade"><div class="section-heading"><div><p class="eyebrow">02 / Авторские изделия</p><h2>Небольшие серии<br>и вещи <em>с характером.</em></h2></div><p>Каждый предмет проходит ручную отливку, обработку или роспись, поэтому двух абсолютно одинаковых работ не бывает.</p></div><div class="material-notes"><article><h3>Свечи</h3><p>Подбираю форму, цвет, аромат и оформление — для отдельного предмета, подарочного набора или события.</p></article><article><h3>Гипсовый декор</h3><p>Отливаю, шлифую и расписываю подносы и небольшие объекты. Рисунок можно подобрать под интерьер или идею подарка.</p></article><article><h3>Картины</h3><p>Работаю с рельефом, цветом и светом. Такие картины меняются в течение дня и особенно хорошо живут в интерьере.</p></article></div><div class="handmade-grid">{figures(handmade[:6])}</div><details class="more-work"><summary>Показать ещё 5 работ</summary><div class="handmade-grid">{figures(handmade[6:])}</div></details></section>
{divider('ribbons')}
<section id="printing" class="printing noise-panel"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">03 / 3D-печать</p><h2>Когда готовой вещи<br>ещё <em>не существует.</em></h2></div><p>Печатаю прототипы, декор и функциональные детали. До старта обсуждаем модель, размеры, материал и ожидаемый результат.</p></div><p class="lead narrow">3D-печать особенно полезна, когда нужно проверить форму перед небольшой серией, восстановить отдельную деталь или изготовить объект под конкретное пространство.</p><div class="printer-grid"><article><span class="eyebrow">Оборудование / 01</span><h3>Bambu Lab A1</h3><p>Открытый FDM-принтер с автоматической калибровкой и рабочей областью 256 × 256 × 256 мм. Использую для прототипов, декора и повседневных изделий из подходящих материалов.</p><a href="https://bambulab.com/en/a1/tech-specs" target="_blank" rel="noopener">Характеристики производителя ↗</a></article><article><span class="eyebrow">Оборудование / 02</span><h3>QIDI Q2</h3><p>Закрытый принтер с активно нагреваемой камерой. Он расширяет выбор материалов и подходит для задач, где важны стабильная температура и более сложные требования к печати.</p><a href="https://qidi3d.com/products/qidi-q2" target="_blank" rel="noopener">Характеристики производителя ↗</a></article></div><div class="samples-grid">{figures([('print-01-lamp.webp','Декоративный светильник'),('print-02-organizer.webp','Настольный органайзер'),('print-03-bag.webp','Декоративный объект в форме сумки')])}</div><p class="small">На изображениях — примеры возможных предметов. Материал, размеры, модель, стоимость и возможность изготовления согласовываются до печати.</p><div class="order-panel"><h3>Как начинается заказ</h3><ol class="steps"><li><strong>Расскажите о задаче</strong><p>Пришлите описание, эскиз или пример и укажите необходимые размеры.</p></li><li><strong>Согласуем решение</strong><p>Обсудим модель, материал, внешний вид, стоимость и срок.</p></li><li><strong>Напечатаю и проверю</strong><p>После печати проверю деталь и подготовлю её к передаче.</p></li></ol><div class="printing-guide">{mascot("workshop-sit","printing-character")}<p>Если готовой модели нет, сначала обсудим, что потребуется для её подготовки.</p></div></div></div></section><section class="wrap workshop-final"><div><p class="eyebrow">Обсудить идею</p><h2>Что вам хочется<br><em>сделать?</em></h2><p>Можно прийти на мастер-класс, выбрать готовую работу или рассказать мне об индивидуальном заказе.</p>{btn('https://vk.ru/hutorokdesign','Написать в «Хуторок»','solid','target="_blank" rel="noopener"')}</div>{mascot('workshop-vase')}{decor('knot','workshop-final-decor')}</section></main>{footer()}'''

if __name__=='__main__':
 (R/'index.html').write_text(home(),encoding='utf-8')
 for n,k in enumerate(D): (R/'projects'/f'{k}.html').write_text(case(k,n),encoding='utf-8')
 (R/'workshop.html').write_text(workshop(),encoding='utf-8')
 print('Built six pages.')
